name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*' # v1.0.0 などのタグを push すると実行

permissions:
  contents: read
  packages: write # これが必須

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # ここでregistry-urlを指定しておくとnpm/pnpmコマンドが自動でnpm.pkg.github.comを使用
          registry-url: 'https://npm.pkg.github.com'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Publish
        # publishConfigにregistryがある場合は --registry指定は不要。ただ明示的に指定するケースもある
        run: pnpm publish
        env:
          # GITHUB_TOKENは自動でActionsに渡されるが、pnpm/npmが使用するトークンはこの変数を参照
          # setup-node@v4 の registry-url 設定によって自動的に .npmrc が書き換わるので
          # NODE_AUTH_TOKEN を指定しなくても動く可能性はありますが、明示的に指定しておくのが無難です
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
